import Auth from './Auth';
import About from './About';
import Users from './Users';
import UserForm from './UserForm';
import Home from './Home';
import ClassRoom from './ClassRoom';
import ClassRoomForm from './ClassRoomForm';
import Student from './Student';
import StudentForm from './StudentForm';
import Teacher from './Teacher';
import TeacherForm from './TeacherForm';
import Subject from './Subject';
import SubjectForm from './SubjectForm';
import ClassDetail from './ClassDetail';
import ClassAddStudent from './ClassAddStudent';
import TeacherDetail from './TeacherDetail';
import TeacherAddSubject from './TeacherAddSubject';
import TeacherSubjectDetail from './TeacherSubjectDetail';
import ExamForm from './ExamForm';
import ExamType from './ExamType';
import ExamTypeForm from './ExamTypeForm';
import TeacherExamDetail from './TeacherExamDetail';
import AcademicYear from './AcademicYear';
import AcademicYearForm from './AcademicYearForm';
import SchoolInfo from './SchoolInfo';
import SchoolInfoForm from './SchoolInfoForm';
export const AuthScreen = Auth;
export const AboutScreen = About;
export const UsersScreen = Users;
export const UserFormScreen = UserForm;
export const HomeScreen = Home;
export const ClassScreen = ClassRoom;
export const ClassFormScreen = ClassRoomForm;
export const StudentScreen = Student;
export const StudentFormScreen = StudentForm;
export const TeacherScreen = Teacher;
export const TeacherFormScreen = TeacherForm;
export const SubjectScreen = Subject;
export const SubjectFormScreen = SubjectForm;
export const ClassDetailScreen = ClassDetail;
export const ClassAddStudentScreen = ClassAddStudent;
export const TeacherDetailScreen = TeacherDetail;
export const TeacherAddSubjectScreen = TeacherAddSubject;
export const TeacherSubjectDetailScreen = TeacherSubjectDetail;
export const ExamFormScreen = ExamForm;
export const ExamTypeScreen = ExamType;
export const ExamTypeFormScreen = ExamTypeForm;
export const TeacherExamDetailScreen = TeacherExamDetail;
export const AcademicYearScreen = AcademicYear;
export const AcademicYearFormScreen = AcademicYearForm;
export const SchoolInfoScreen = SchoolInfo;
export const SchoolInfoFormScreen = SchoolInfoForm;
