import Auth from './Auth';
import About from './About';
import Users from './Users';
import Home from './Home';
import ClassRoom from './ClassRoom';
import ClassRoomForm from './ClassRoomForm';
import Student from './Student';
import StudentForm from './StudentForm';
import Teacher from './Teacher';
import TeacherForm from './TeacherForm';
import Subject from './Subject';
import SubjectForm from './SubjectForm';
import ClassDetail from './ClassDetail';
import ClassAddStudent from './ClassAddStudent';
export const AuthScreen = Auth;
export const AboutScreen = About;
export const UsersScreen = Users;
export const HomeScreen = Home;
export const ClassScreen = ClassRoom;
export const ClassFormScreen = ClassRoomForm;
export const StudentScreen = Student;
export const StudentFormScreen = StudentForm;
export const TeacherScreen = Teacher;
export const TeacherFormScreen = TeacherForm;
export const SubjectScreen = Subject;
export const SubjectFormScreen = SubjectForm;
export const ClassDetailScreen = ClassDetail;
export const ClassAddStudentScreen = ClassAddStudent;
